### ISSUE TITLE
Rails 4.1.4 "ArgumentError: Unknown key: :order"

### ISSUE THREAD

**Issue by eriknomitch** [elight/acts_as_commentable_with_threading#81]
`ArgumentError: Unknown key: :order` is happening on `Comment.all` and the commentable model's `.comment_threads` and `.root_comments` methods in Rails 4.1.4.

```
[1] pry(main)> Comment.all
ArgumentError: Unknown key: :order. Valid keys are: :class_name, :class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table
from /Users/erik/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/core_ext/hash/keys.rb:71:in `block in assert_valid_keys'
[2] pry(main)> Post.last.comment_threads
  Post Load (0.1ms)  SELECT  "posts".* FROM "posts"   ORDER BY "posts"."id" DESC LIMIT 1
ArgumentError: Unknown key: :order. Valid keys are: :class_name, :class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table
from /Users/erik/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/core_ext/hash/keys.rb:71:in `block in assert_valid_keys'
```

Edit: I'd really like to add this into [Prelang](http://prelang.com) as soon as possible.

**Comment by vivek2007** [comment]
gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/hash/keys.rb:75:in `block in assert_valid_keys': Unknown key: :order. Valid keys are: :class_name, :class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type (ArgumentError)

**Comment by gonuguntla** [comment]
gem 'awesome_nested_set', '2.0.0' -  I used same way. Still  facing same issue.
