### ISSUE TITLE
Illustrative tutorial on implementing the gem

### ISSUE THREAD

**Issue by damienh** [elight/acts_as_commentable_with_threading#83]
Hi,

I have had a look around and cannot find a decent tutorial showing you how you can go about implementing this gem for a fully commendable model with threaded replies. If anyone knows of one I would be in your debt. 

Damien

**Comment by DustinFisher** [comment]
I know this is an older issue, but I will throw this up here if someone else comes across this and looking for an example.

I worked through pieces and parts I found across the web and got threading working. I put a guide together showing how to get up and running.

Here is the example I put together: [acts_as_commentable_with_threading example](http://dustinfisher.com/acts-as-commentable-with-threading-gem/)

**Comment by richardnpnb** [comment]
DustinFisher's guide is well written. The best I have found for this gem.
